include: package:pedantic/analysis_options.yaml

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: true

  enable-experiment:
    - non-nullable

  errors:
    todo: ignore
    dead_code: error

linter:
  rules:
