name: model
version: 0.0.1
description: ->
  Create models of database tables.
homepage: https://github.com/romanstrazanec/model
repository: https://github.com/romanstrazanec/model

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
