name: model
version: 0.1.3-nullsafety.1
description: Manage database easier. Use models to represent rows of database.
  Create database structure using object-oriented dart and leave all SQL strings hidden.
homepage: https://github.com/romanstrazanec/model
repository: https://github.com/romanstrazanec/model

environment:
  sdk: ">=2.11.0-213.0.dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  path: any
  sqflite: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: any

flutter:
